### ISSUE TITLE
`byte` allocates uninitialized buffers and reads data from them past the initialized length

### ISSUE THREAD

**Issue by ChALkeR** [node-modules/byte#33]
Refs:
* https://hackerone.com/reports/330351
* https://github.com/nodejs/security-wg/blob/master/vuln/npm/429.json
* https://snyk.io/vuln/npm:byte:20180512

---

`byte` allocates uninitialized buffers on all Node.js versions, even on the ones that zero-full `new Buffer()` by default, as it uses `.allocUnsafe()`. It provides an API for writing data and an API for reading data from the buffer, but the internal buffer is not zero-filled and the API for reading does not validate that the memory being read was ever initialized.

I also don't think this corresponds to behavior  of the Java ByteBuffer — that one is zero-filled afaik.

#### Steps To Reproduce:

```js
var ByteBuffer = require('byte');
for (let k = 0; k < 1e4; k++) {
  var bb = new ByteBuffer();
  for (let i = 0; i < 180; i++) {
    bb.putString('ok');
  }
  const s = bb.getString(1000);
  if (s.includes(' {')) {
    console.log(s);
    console.log('Finished at attempt: ' + k);
    break;
  }
}
```

```js
var ByteBuffer = require('byte');
for (let k = 0; k < 1e4; k++) {
  var bb = ByteBuffer.allocate(50);
  const twos = Buffer.alloc(10, 2);
  for (let i = 0; i < 7; i++) bb.put(twos, 10);
  const s = bb.get(0, 100);
  if (s.includes(' {')) {
    console.log(s.toString('utf-8'));
    console.log('Finished at attempt: ' + k);
    break;
  }
}
```

#### Patch

Replace all `Buffer(num)` and `Buffer.allocUnsafe(num)` usage with `Buffer.alloc(num)` and use a polyfill, e.g. [safer-buffer](https://www.npmjs.com/package/safer-buffer) or [buffer-alloc](https://www.npmjs.com/package/buffer-alloc).

Perhaps other fixes in logic might be needed, but the above patch would solve the uninitialized memory exposure.

**Comment by denghongcai** [comment]
IMO, every hacky operation on `bytes` should pay attention to buffer boundary itself. `bytes` read and write is based on internal r/w cursor. It won't read/write on unsafe buffer.

**Comment by fengmk2** [comment]
fixed on https://github.com/node-modules/byte/pull/34
